name: Release Manual

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        default: 'manual-release'
      container_name:
        description: 'Container to release (leave empty for all)'
        required: false
        default: ''
        
jobs:
  simple-checks:
    uses: flov91/containers/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    needs: ["simple-checks"]
    uses: flov91/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    # if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: flov91/containers/.github/workflows/build-images.yaml@main
    secrets: inherit
    with:
      # appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    if: ${{ always() && needs.build-images.result != 'failure' }}
    uses: ./.github/workflows/render-readme.yaml
    secrets: inherit
